import type { SuggestionItem } from "./types";

export const TRADE_FIELD_SUGGESTIONS: SuggestionItem[] = [
  {
    id: "symbol",
    name: "symbol",
    type: "field",
    description: "Trading instrument",
    category: "Core",
  },
  {
    id: "tradeType",
    name: "trade direction",
    type: "field",
    description: "Long or short",
    category: "Core",
  },
  {
    id: "outcome",
    name: "outcome",
    type: "field",
    description: "Win, loss, break-even",
    category: "Core",
  },
  {
    id: "profit",
    name: "profit",
    type: "field",
    description: "Net profit or loss",
    category: "Core",
  },
  {
    id: "open",
    name: "open time",
    type: "field",
    description: "Trade entry time",
    category: "Core",
  },
  {
    id: "close",
    name: "close time",
    type: "field",
    description: "Trade exit time",
    category: "Core",
  },
  {
    id: "tradeDurationSeconds",
    name: "hold time",
    type: "field",
    description: "Time in trade",
    category: "Timing",
  },
  {
    id: "volume",
    name: "volume",
    type: "field",
    description: "Position size",
    category: "Execution",
  },
  {
    id: "commissions",
    name: "commissions",
    type: "field",
    description: "Broker fees",
    category: "Execution",
  },
  {
    id: "swap",
    name: "swap",
    type: "field",
    description: "Overnight swap",
    category: "Execution",
  },
  {
    id: "entrySpreadPips",
    name: "entry spread",
    type: "field",
    description: "Bid-ask spread at entry",
    category: "Execution",
  },
  {
    id: "exitSpreadPips",
    name: "exit spread",
    type: "field",
    description: "Bid-ask spread at exit",
    category: "Execution",
  },
  {
    id: "entrySlippagePips",
    name: "entry slippage",
    type: "field",
    description: "Slippage at entry",
    category: "Execution",
  },
  {
    id: "exitSlippagePips",
    name: "exit slippage",
    type: "field",
    description: "Slippage at exit",
    category: "Execution",
  },
  {
    id: "sessionTag",
    name: "session tag",
    type: "field",
    description: "Session or window",
    category: "Tags",
  },
  {
    id: "modelTag",
    name: "model tag",
    type: "field",
    description: "Strategy label",
    category: "Tags",
  },
  {
    id: "protocolAlignment",
    name: "protocol alignment",
    type: "field",
    description: "Rule adherence",
    category: "Tags",
  },
  {
    id: "plannedRR",
    name: "planned rr",
    type: "field",
    description: "Planned reward to risk",
    category: "Tags",
  },
  {
    id: "realisedRR",
    name: "realised rr",
    type: "field",
    description: "Actual reward to risk",
    category: "Execution",
  },
  {
    id: "maxRR",
    name: "max rr",
    type: "field",
    description: "Peak reward to risk",
    category: "Opportunity",
  },
  {
    id: "rrCaptureEfficiency",
    name: "rr capture efficiency",
    type: "field",
    description: "Efficiency of capture",
    category: "Efficiency",
  },
  {
    id: "exitEfficiency",
    name: "exit efficiency",
    type: "field",
    description: "Exit quality",
    category: "Efficiency",
  },
  {
    id: "mfePips",
    name: "mfe",
    type: "field",
    description: "Max favorable excursion",
    category: "Opportunity",
  },
  {
    id: "maePips",
    name: "mae",
    type: "field",
    description: "Max adverse excursion",
    category: "Risk",
  },
  {
    id: "stdvBucket",
    name: "volatility bucket",
    type: "field",
    description: "Volatility category",
    category: "Opportunity",
  },
  {
    id: "rawSTDV",
    name: "standard deviation",
    type: "field",
    description: "Raw price std dev",
    category: "Opportunity",
  },
  {
    id: "manipulationPips",
    name: "manipulation pips",
    type: "field",
    description: "Manipulation size",
    category: "Opportunity",
  },
  {
    id: "mpeManipPE_R",
    name: "post exit mpe r",
    type: "field",
    description: "Post-exit continuation",
    category: "Opportunity",
  },
  {
    id: "mpeManipLegR",
    name: "mpe manipulation leg r",
    type: "field",
    description: "MPE from manipulation leg",
    category: "Opportunity",
  },
  {
    id: "manipulationHigh",
    name: "manipulation high",
    type: "field",
    description: "Manipulation range high",
    category: "Opportunity",
  },
  {
    id: "manipulationLow",
    name: "manipulation low",
    type: "field",
    description: "Manipulation range low",
    category: "Opportunity",
  },
  {
    id: "manipulationPips",
    name: "manipulation size",
    type: "field",
    description: "Manipulation size in pips",
    category: "Opportunity",
  },
  {
    id: "entryPeakDurationSeconds",
    name: "time to peak",
    type: "field",
    description: "Entry to peak duration",
    category: "Timing",
  },
  {
    id: "postExitPeakDurationSeconds",
    name: "post exit time to peak",
    type: "field",
    description: "Exit to post-exit peak duration",
    category: "Timing",
  },
  {
    id: "mfePips",
    name: "maximum favorable excursion",
    type: "field",
    description: "MFE in pips",
    category: "Opportunity",
  },
  {
    id: "maePips",
    name: "maximum adverse excursion",
    type: "field",
    description: "MAE in pips",
    category: "Risk",
  },
  {
    id: "plannedTargetPips",
    name: "planned target pips",
    type: "field",
    description: "Planned target distance",
    category: "Intent",
  },
  {
    id: "plannedRiskPips",
    name: "planned risk pips",
    type: "field",
    description: "Planned risk distance",
    category: "Intent",
  },
  {
    id: "plannedRR",
    name: "planned rr",
    type: "field",
    description: "Planned reward to risk",
    category: "Intent",
  },
  {
    id: "entryBalance",
    name: "balance at entry",
    type: "field",
    description: "Account balance at entry",
    category: "Risk",
  },
  {
    id: "entryEquity",
    name: "equity at entry",
    type: "field",
    description: "Account equity at entry",
    category: "Risk",
  },
  {
    id: "entryMargin",
    name: "margin at entry",
    type: "field",
    description: "Margin used at entry",
    category: "Risk",
  },
  {
    id: "entryFreeMargin",
    name: "free margin at entry",
    type: "field",
    description: "Free margin at entry",
    category: "Risk",
  },
  {
    id: "entryMarginLevel",
    name: "margin level at entry",
    type: "field",
    description: "Margin level percent",
    category: "Risk",
  },
  {
    id: "scaleInCount",
    name: "scale in count",
    type: "field",
    description: "Scale-in count",
    category: "Execution",
  },
  {
    id: "scaleOutCount",
    name: "scale out count",
    type: "field",
    description: "Scale-out count",
    category: "Execution",
  },
  {
    id: "partialCloseCount",
    name: "partial closes",
    type: "field",
    description: "Partial exits",
    category: "Execution",
  },
];
