import type { SuggestionItem } from "./types";

export const TRADE_COMMAND_SUGGESTIONS: SuggestionItem[] = [
  {
    id: "win-rate",
    name: "What's my win rate?",
    type: "query",
    description: "Overall win rate",
    category: "Overview",
  },
  {
    id: "profit-factor",
    name: "What's my profit factor?",
    type: "query",
    description: "Profit factor across all trades",
    category: "Overview",
  },
  {
    id: "avg-hold-time",
    name: "How long do I hold trades on average?",
    type: "query",
    description: "Average hold time",
    category: "Overview",
  },
  {
    id: "most-profitable-asset",
    name: "What's my most profitable asset?",
    type: "query",
    description: "Top asset by total profit",
    category: "Assets",
  },
  {
    id: "least-profitable-asset",
    name: "What's my least profitable asset?",
    type: "query",
    description: "Bottom asset by total profit",
    category: "Assets",
  },
  {
    id: "profit-by-asset",
    name: "Breakdown by symbol",
    type: "query",
    description: "Total profit by symbol",
    category: "Assets",
  },
  {
    id: "trades-this-week",
    name: "Show me my trades this week",
    type: "query",
    description: "List trades over the past 7 days",
    category: "Activity",
  },
  {
    id: "performance-week",
    name: "What's my performance this week?",
    type: "query",
    description: "Daily net cumulative P&L",
    category: "Activity",
  },
  {
    id: "weekday-performance",
    name: "Performance by day of week",
    type: "query",
    description: "Profit by weekday",
    category: "Timing",
  },
  {
    id: "session-performance",
    name: "Performance by session",
    type: "query",
    description: "Profit by session tag",
    category: "Sessions",
  },
  {
    id: "compare-sessions",
    name: "Compare NY vs London session",
    type: "query",
    description: "Compare session performance",
    category: "Sessions",
  },
  {
    id: "losses-commission",
    name: "How much am I losing to commissions?",
    type: "query",
    description: "Commissions and swap total",
    category: "Costs",
  },
  {
    id: "costs-breakdown",
    name: "Trading costs breakdown",
    type: "query",
    description: "Commissions, swap, and losses",
    category: "Costs",
  },
  {
    id: "rr-capture",
    name: "What's my rr capture efficiency?",
    type: "query",
    description: "Capture efficiency",
    category: "Execution",
  },
  {
    id: "exit-efficiency",
    name: "What's my exit efficiency?",
    type: "query",
    description: "Exit timing quality",
    category: "Execution",
  },
  {
    id: "mfe-mae",
    name: "Average MFE vs MAE",
    type: "query",
    description: "MFE/MAE comparison",
    category: "Opportunity",
  },
  {
    id: "post-exit",
    name: "How much did I leave on the table?",
    type: "query",
    description: "Post-exit MPE",
    category: "Opportunity",
  },
  {
    id: "model-performance",
    name: "Performance by model tag",
    type: "query",
    description: "Profit by model",
    category: "Models",
  },
  {
    id: "protocol-alignment",
    name: "Performance by protocol alignment",
    type: "query",
    description: "Aligned vs against vs discretionary",
    category: "Models",
  },
  {
    id: "post-loss-temporal",
    name: "After a loss, how do my next 5 trades perform?",
    type: "query",
    description: "Post-loss cohort vs baseline",
    category: "Temporal",
  },
  {
    id: "ny-loss-temporal",
    name: "After a loss in New York, what happens next?",
    type: "query",
    description: "Post-loss NY cohort comparison",
    category: "Temporal",
  },
  {
    id: "win-streak-temporal",
    name: "After a win streak, how do my next 3 trades perform?",
    type: "query",
    description: "Post-streak cohort comparison",
    category: "Temporal",
  },
  {
    id: "hidden-states",
    name: "Find my trading states",
    type: "query",
    description: "Cluster trades into behavior states",
    category: "States",
  },
  {
    id: "hidden-states-top",
    name: "Which trading state performs best?",
    type: "query",
    description: "Best-performing hidden state",
    category: "States",
  },
  {
    id: "persona-shift",
    name: "How am I trading differently now vs 3 months ago?",
    type: "query",
    description: "Persona tracking over time",
    category: "Persona",
  },
  {
    id: "persona-trend",
    name: "Show my trading persona over time",
    type: "query",
    description: "Rolling persona metrics",
    category: "Persona",
  },
  {
    id: "journal-patterns",
    name: "What patterns keep showing up in my journal?",
    type: "query",
    description: "Journal strengths, weaknesses, and recurring themes",
    category: "Journal",
  },
  {
    id: "backtest-drift",
    name: "Where does my backtest behavior drift from live?",
    type: "query",
    description: "Backtest vs live execution drift",
    category: "Backtest",
  },
  {
    id: "prop-risk",
    name: "How close am I to failing my prop challenge?",
    type: "query",
    description: "Prop rule headroom and failure risk",
    category: "Prop",
  },
  {
    id: "dashboard-focus",
    name: "What's the one thing I should focus on today?",
    type: "query",
    description: "Cross-dashboard priority call",
    category: "Coaching",
  },
];
