import type { SuggestionItem } from "./types";

export const TRADE_COMMAND_SUGGESTIONS: SuggestionItem[] = [
  {
    id: "win-rate",
    name: "What's my win rate?",
    type: "query",
    description: "Overall win rate",
    category: "Overview",
  },
  {
    id: "profit-factor",
    name: "What's my profit factor?",
    type: "query",
    description: "Profit factor across all trades",
    category: "Overview",
  },
  {
    id: "avg-hold-time",
    name: "How long do I hold trades on average?",
    type: "query",
    description: "Average hold time",
    category: "Overview",
  },
  {
    id: "most-profitable-asset",
    name: "What's my most profitable asset?",
    type: "query",
    description: "Top asset by total profit",
    category: "Assets",
  },
  {
    id: "least-profitable-asset",
    name: "What's my least profitable asset?",
    type: "query",
    description: "Bottom asset by total profit",
    category: "Assets",
  },
  {
    id: "profit-by-asset",
    name: "Breakdown by symbol",
    type: "query",
    description: "Total profit by symbol",
    category: "Assets",
  },
  {
    id: "trades-this-week",
    name: "Show me my trades this week",
    type: "query",
    description: "List trades over the past 7 days",
    category: "Activity",
  },
  {
    id: "performance-week",
    name: "What's my performance this week?",
    type: "query",
    description: "Daily net cumulative P&L",
    category: "Activity",
  },
  {
    id: "weekday-performance",
    name: "Performance by day of week",
    type: "query",
    description: "Profit by weekday",
    category: "Timing",
  },
  {
    id: "session-performance",
    name: "Performance by session",
    type: "query",
    description: "Profit by session tag",
    category: "Sessions",
  },
  {
    id: "compare-sessions",
    name: "Compare NY vs London session",
    type: "query",
    description: "Compare session performance",
    category: "Sessions",
  },
  {
    id: "losses-commission",
    name: "How much am I losing to commissions?",
    type: "query",
    description: "Commissions and swap total",
    category: "Costs",
  },
  {
    id: "costs-breakdown",
    name: "Trading costs breakdown",
    type: "query",
    description: "Commissions, swap, and losses",
    category: "Costs",
  },
  {
    id: "rr-capture",
    name: "What's my rr capture efficiency?",
    type: "query",
    description: "Capture efficiency",
    category: "Execution",
  },
  {
    id: "exit-efficiency",
    name: "What's my exit efficiency?",
    type: "query",
    description: "Exit timing quality",
    category: "Execution",
  },
  {
    id: "mfe-mae",
    name: "Average MFE vs MAE",
    type: "query",
    description: "MFE/MAE comparison",
    category: "Opportunity",
  },
  {
    id: "post-exit",
    name: "How much did I leave on the table?",
    type: "query",
    description: "Post-exit MPE",
    category: "Opportunity",
  },
  {
    id: "model-performance",
    name: "Performance by model tag",
    type: "query",
    description: "Profit by model",
    category: "Models",
  },
  {
    id: "protocol-alignment",
    name: "Performance by protocol alignment",
    type: "query",
    description: "Aligned vs against vs discretionary",
    category: "Models",
  },
  {
    id: "post-loss-temporal",
    name: "After a loss, how do my next 5 trades perform?",
    type: "query",
    description: "Post-loss cohort vs baseline",
    category: "Temporal",
  },
  {
    id: "ny-loss-temporal",
    name: "After a loss in New York, what happens next?",
    type: "query",
    description: "Post-loss NY cohort comparison",
    category: "Temporal",
  },
  {
    id: "win-streak-temporal",
    name: "After a win streak, how do my next 3 trades perform?",
    type: "query",
    description: "Post-streak cohort comparison",
    category: "Temporal",
  },
  {
    id: "hidden-states",
    name: "Find my trading states",
    type: "query",
    description: "Cluster trades into behavior states",
    category: "States",
  },
  {
    id: "hidden-states-top",
    name: "Which trading state performs best?",
    type: "query",
    description: "Best-performing hidden state",
    category: "States",
  },
  {
    id: "persona-shift",
    name: "How am I trading differently now vs 3 months ago?",
    type: "query",
    description: "Persona tracking over time",
    category: "Persona",
  },
  {
    id: "persona-trend",
    name: "Show my trading persona over time",
    type: "query",
    description: "Rolling persona metrics",
    category: "Persona",
  },
  {
    id: "journal-patterns",
    name: "What patterns keep showing up in my journal?",
    type: "query",
    description: "Journal strengths, weaknesses, and recurring themes",
    category: "Journal",
  },
  {
    id: "prop-risk",
    name: "How close am I to failing my prop challenge?",
    type: "query",
    description: "Prop rule headroom and failure risk",
    category: "Prop",
  },
  {
    id: "dashboard-focus",
    name: "What's the one thing I should focus on today?",
    type: "query",
    description: "Cross-dashboard priority call",
    category: "Coaching",
  },
  {
    id: "session-direction-best",
    name: "Which session-direction combo has my highest win rate?",
    type: "query",
    description: "Best session and long/short combination",
    category: "Intersections",
  },
  {
    id: "session-direction-profit",
    name: "Am I better at shorts during London and longs during New York?",
    type: "query",
    description: "Session and direction combo profitability",
    category: "Intersections",
  },
  {
    id: "symbol-session-direction",
    name: "Which symbol-session-direction combo is my most profitable setup?",
    type: "query",
    description: "Best symbol, session, and direction combination",
    category: "Intersections",
  },
  {
    id: "edge-protocol-winrate",
    name: "When I follow my Edge rules and trade aligned, what's my win rate?",
    type: "query",
    description: "Edge plus protocol-alignment performance",
    category: "Intersections",
  },
  {
    id: "edge-against-protocol",
    name: "Which Edge has the most against-protocol trades?",
    type: "query",
    description: "Edge ranking by protocol deviation",
    category: "Intersections",
  },
  {
    id: "edge-winner-rr",
    name: "Which Edge produces the highest average R on winners?",
    type: "query",
    description: "Winner-only average R by Edge",
    category: "Intersections",
  },
  {
    id: "edge-expectancy",
    name: "Which Edge has the best expectancy?",
    type: "query",
    description: "Win rate and expectancy by Edge",
    category: "Intersections",
  },
  {
    id: "session-hold-outcome",
    name: "What's the ideal hold time per session?",
    type: "query",
    description: "Average hold time by session and outcome",
    category: "Intersections",
  },
  {
    id: "direction-mae-mfe",
    name: "Do my longs have deeper drawdown before going in my favor?",
    type: "query",
    description: "MAE and MFE comparison by direction",
    category: "Intersections",
  },
  {
    id: "protocol-pnl",
    name: "How much total money have I lost on against-protocol trades?",
    type: "query",
    description: "P&L cost of non-aligned trades",
    category: "Intersections",
  },
  {
    id: "protocol-winrate-compare",
    name: "What's my win rate on aligned vs discretionary trades?",
    type: "query",
    description: "Protocol-alignment cohort comparison",
    category: "Intersections",
  },
  {
    id: "edge-compliance",
    name: "Which Edge has the most compliance failures?",
    type: "query",
    description: "Compliance breakdown by Edge",
    category: "Intersections",
  },
  {
    id: "volatility-direction-symbol",
    name: "Am I profitable on gold in high volatility but losing in low?",
    type: "query",
    description: "Volatility, direction, and symbol breakdown",
    category: "Intersections",
  },
  {
    id: "capture-edge-gap",
    name: "Which Edge am I leaving the most R on the table?",
    type: "query",
    description: "Capture and exit-efficiency gap by Edge",
    category: "Intersections",
  },
  {
    id: "spread-session-symbol",
    name: "Which symbol-session combo has the worst spreads at entry?",
    type: "query",
    description: "Spread costs by symbol and session",
    category: "Intersections",
  },
  {
    id: "trailing-stop-efficiency",
    name: "Do trailing stops help me capture more of the max R:R?",
    type: "query",
    description: "Trailing-stop effect on realised vs max R",
    category: "Intersections",
  },
  {
    id: "partial-close-symbol",
    name: "Which symbols benefit most from scaling out?",
    type: "query",
    description: "Partial closes and R:R by symbol",
    category: "Intersections",
  },
  {
    id: "slippage-volume-session",
    name: "Which session gives me the least slippage on my most traded symbol?",
    type: "query",
    description: "Slippage, volume, symbol, and session interaction",
    category: "Intersections",
  },
];
