"use client";

export {
  PromptInputProvider,
  usePromptInputController,
  useProviderAttachments,
  usePromptInputAttachments,
  type AttachmentsContext,
  type PromptInputControllerProps,
  type PromptInputProviderProps,
  type TextInputContext,
} from "@/features/ai/prompt-input/lib/prompt-input-context";
export {
  PromptInputAttachment,
  PromptInputAttachments,
  PromptInputActionAddAttachments,
  type PromptInputAttachmentProps,
  type PromptInputAttachmentsProps,
  type PromptInputActionAddAttachmentsProps,
} from "@/features/ai/prompt-input/components/prompt-input-attachments";
export {
  PromptInput,
  PromptInputTextarea,
  type PromptInputMessage,
  type PromptInputProps,
  type PromptInputTextareaProps,
} from "@/features/ai/prompt-input/components/prompt-input-root";
export {
  PromptInputBody,
  PromptInputHeader,
  PromptInputFooter,
  PromptInputTools,
  PromptInputButton,
  PromptInputActionMenuTrigger,
  type PromptInputBodyProps,
  type PromptInputHeaderProps,
  type PromptInputFooterProps,
  type PromptInputToolsProps,
  type PromptInputButtonProps,
  type PromptInputActionMenuTriggerProps,
} from "@/features/ai/prompt-input/components/prompt-input-layout";
export {
  PromptInputSubmit,
  PromptInputSpeechButton,
  type PromptInputSubmitProps,
  type PromptInputSpeechButtonProps,
} from "@/features/ai/prompt-input/components/prompt-input-actions";
export {
  PromptInputActionMenu,
  PromptInputActionMenuContent,
  PromptInputActionMenuItem,
  PromptInputSelect,
  PromptInputSelectTrigger,
  PromptInputSelectContent,
  PromptInputSelectItem,
  PromptInputSelectValue,
  PromptInputHoverCard,
  PromptInputHoverCardTrigger,
  PromptInputHoverCardContent,
  PromptInputTabsList,
  PromptInputTab,
  PromptInputTabLabel,
  PromptInputTabBody,
  PromptInputTabItem,
  PromptInputCommand,
  PromptInputCommandInput,
  PromptInputCommandList,
  PromptInputCommandEmpty,
  PromptInputCommandGroup,
  PromptInputCommandItem,
  PromptInputCommandSeparator,
  type PromptInputActionMenuProps,
  type PromptInputActionMenuContentProps,
  type PromptInputActionMenuItemProps,
  type PromptInputSelectProps,
  type PromptInputSelectTriggerProps,
  type PromptInputSelectContentProps,
  type PromptInputSelectItemProps,
  type PromptInputSelectValueProps,
  type PromptInputHoverCardProps,
  type PromptInputHoverCardTriggerProps,
  type PromptInputHoverCardContentProps,
  type PromptInputTabsListProps,
  type PromptInputTabProps,
  type PromptInputTabLabelProps,
  type PromptInputTabBodyProps,
  type PromptInputTabItemProps,
  type PromptInputCommandProps,
  type PromptInputCommandInputProps,
  type PromptInputCommandListProps,
  type PromptInputCommandEmptyProps,
  type PromptInputCommandGroupProps,
  type PromptInputCommandItemProps,
  type PromptInputCommandSeparatorProps,
} from "@/features/ai/prompt-input/components/prompt-input-elements";
