import {
  pgTable,
  text,
  timestamp,
  integer,
  varchar,
  boolean,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { user } from "./auth";
import { tradingAccount, openTrade } from "./trading";

// ─── Trader Profile ─────────────────────────────────────────────
// One row per account. Stores the computed behavioral snapshot.
// Recomputed when new trades close or every 30 minutes.

export const traderProfile = pgTable(
  "trader_profile",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    accountId: text("account_id")
      .notNull()
      .references(() => tradingAccount.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    // Snapshot metadata
    computedAt: timestamp("computed_at").notNull().defaultNow(),
    tradeCountAtCompute: integer("trade_count_at_compute").notNull().default(0),

    // Behavioral snapshot (TraderProfileData)
    profileData: jsonb("profile_data").notNull(),

    // Edge conditions — winning combos (EdgeCondition[])
    edgeConditions: jsonb("edge_conditions").notNull().default([]),

    // Leak conditions — losing combos (LeakCondition[])
    leakConditions: jsonb("leak_conditions").notNull().default([]),

    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
  },
  (table) => ({
    accountIdUniqueIdx: uniqueIndex("idx_trader_profile_account_id").on(
      table.accountId
    ),
    userIdIdx: index("idx_trader_profile_user_id").on(table.userId),
  })
);

export type TraderProfileRow = typeof traderProfile.$inferSelect;
export type InsertTraderProfile = typeof traderProfile.$inferInsert;

// ─── Trader Insight ─────────────────────────────────────────────
// Proactive insights generated by the insight engine.
// Displayed in the dashboard insight panel.

export const traderInsight = pgTable(
  "trader_insight",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    accountId: text("account_id")
      .notNull()
      .references(() => tradingAccount.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),

    category: varchar("category", { length: 30 }).notNull(), // behavioral | efficiency | risk | pattern | anomaly | positive
    severity: varchar("severity", { length: 20 }).notNull(), // critical | warning | info | positive
    title: text("title").notNull(),
    message: text("message").notNull(),
    recommendation: text("recommendation"),
    data: jsonb("data"), // Supporting numbers/evidence

    isRead: boolean("is_read").notNull().default(false),
    isDismissed: boolean("is_dismissed").notNull().default(false),
    readAt: timestamp("read_at"),

    // Source context
    triggerType: varchar("trigger_type", { length: 30 }).notNull(), // scheduled | trade_close | manual | live_alert
    triggeredBy: text("triggered_by"), // e.g., trade ID that triggered it

    expiresAt: timestamp("expires_at"), // Insights can expire (e.g., streak alerts)
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => ({
    accountIdIdx: index("idx_trader_insight_account_id").on(table.accountId),
    userIdIdx: index("idx_trader_insight_user_id").on(table.userId),
    unreadIdx: index("idx_trader_insight_unread").on(
      table.accountId,
      table.isRead,
      table.isDismissed
    ),
  })
);

export type TraderInsightRow = typeof traderInsight.$inferSelect;
export type InsertTraderInsight = typeof traderInsight.$inferInsert;

// ─── Trader Alert ───────────────────────────────────────────────
// Live trade deviation alerts.
// Generated when open trades deviate from the trader's profile.

export const traderAlert = pgTable(
  "trader_alert",
  {
    id: text("id")
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    accountId: text("account_id")
      .notNull()
      .references(() => tradingAccount.id, { onDelete: "cascade" }),
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    openTradeId: text("open_trade_id").references(() => openTrade.id, {
      onDelete: "cascade",
    }),

    alertType: varchar("alert_type", { length: 30 }).notNull(), // unusual_hold_time | unusual_session | unusual_symbol | unusual_volume | protocol_deviation | low_score
    severity: varchar("severity", { length: 20 }).notNull(), // critical | warning | info
    title: text("title").notNull(),
    message: text("message").notNull(),
    data: jsonb("data"), // Supporting context

    isRead: boolean("is_read").notNull().default(false),
    isDismissed: boolean("is_dismissed").notNull().default(false),

    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (table) => ({
    accountIdIdx: index("idx_trader_alert_account_id").on(table.accountId),
    userIdIdx: index("idx_trader_alert_user_id").on(table.userId),
    openTradeIdx: index("idx_trader_alert_open_trade").on(table.openTradeId),
    unreadIdx: index("idx_trader_alert_unread").on(
      table.accountId,
      table.isRead,
      table.isDismissed
    ),
  })
);

export type TraderAlertRow = typeof traderAlert.$inferSelect;
export type InsertTraderAlert = typeof traderAlert.$inferInsert;
