"use client";

import { useCallback } from "react";
import { format } from "date-fns";
import type { VizSpec, AnalysisBlock } from "@/types/assistant-stream";

interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  createdAt: Date;
  visualization?: VizSpec;
  analysisBlocks?: AnalysisBlock[];
}

interface ExportOptions {
  title?: string;
  includeVisualizations?: boolean;
  includeAnalysis?: boolean;
}

function stripMarkdown(text: string): string {
  return text
    .replace(/#{1,6}\s+/g, "")
    .replace(/\*\*(.*?)\*\*/g, "$1")
    .replace(/\*(.*?)\*/g, "$1")
    .replace(/`(.*?)`/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/^\s*[-*+]\s+/gm, "• ")
    .replace(/^\s*\d+\.\s+/gm, "")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function usePDFExport() {
  const exportToPDF = useCallback(
    async (messages: ChatMessage[], options: ExportOptions = {}) => {
      const { title = "AI Analysis Report", includeVisualizations = true, includeAnalysis = true } = options;

      const exportContent = document.createElement("div");
      exportContent.id = "pdf-export-container";
      exportContent.style.cssText = `
        position: fixed;
        left: -9999px;
        top: 0;
        width: 800px;
        background: white;
        color: #1a1a1a;
        font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        padding: 40px;
      `;

      const headerHTML = `
        <div style="margin-bottom: 32px; padding-bottom: 24px; border-bottom: 2px solid #e5e7eb;">
          <h1 style="font-size: 28px; font-weight: 700; color: #111827; margin: 0 0 8px 0;">${title}</h1>
          <p style="font-size: 14px; color: #6b7280; margin: 0;">
            Generated on ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}
          </p>
        </div>
      `;

      let messagesHTML = "";
      let analysisHTML = "";

      messages.forEach((message, index) => {
        if (message.role === "user") {
          messagesHTML += `
            <div style="margin-bottom: 24px;">
              <div style="display: inline-block; background: #f3f4f6; padding: 12px 16px; border-radius: 12px; max-width: 80%;">
                <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 4px 0;">Your Question</p>
                <p style="font-size: 14px; color: #1f2937; margin: 0; line-height: 1.6;">${stripMarkdown(message.content)}</p>
              </div>
            </div>
          `;
        } else {
          const cleanContent = stripMarkdown(message.content);
          messagesHTML += `
            <div style="margin-bottom: 24px;">
              <div style="background: #fafafa; border: 1px solid #e5e7eb; padding: 20px; border-radius: 12px;">
                <p style="font-size: 13px; font-weight: 600; color: #7c3aed; margin: 0 0 12px 0;">AI Response</p>
                <div style="font-size: 14px; color: #374151; line-height: 1.7; white-space: pre-wrap;">${cleanContent}</div>
              </div>
            </div>
          `;

          if (includeAnalysis && message.analysisBlocks && message.analysisBlocks.length > 0) {
            message.analysisBlocks.forEach((block) => {
              analysisHTML += formatAnalysisBlock(block);
            });
          }

          if (includeVisualizations && message.visualization) {
            analysisHTML += formatVisualization(message.visualization);
          }
        }
      });

      const footerHTML = `
        <div style="margin-top: 48px; padding-top: 24px; border-top: 1px solid #e5e7eb;">
          <p style="font-size: 12px; color: #9ca3af; margin: 0; text-align: center;">
            Generated by ProfitableEdge AI Assistant • ${format(new Date(), "yyyy")}
          </p>
        </div>
      `;

      exportContent.innerHTML = `
        ${headerHTML}
        <div style="margin-bottom: 32px;">
          <h2 style="font-size: 18px; font-weight: 600; color: #374151; margin: 0 0 16px 0;">Conversation</h2>
          ${messagesHTML}
        </div>
        ${analysisHTML ? `<div style="margin-bottom: 32px;"><h2 style="font-size: 18px; font-weight: 600; color: #374151; margin: 0 0 16px 0;">Analysis Summary</h2>${analysisHTML}</div>` : ""}
        ${footerHTML}
      `;

      document.body.appendChild(exportContent);

      const printWindow = window.open("", "_blank");
      if (printWindow) {
        printWindow.document.write(`
          <!DOCTYPE html>
          <html>
            <head>
              <title>${title}</title>
              <style>
                @media print {
                  body { margin: 0; padding: 20px; }
                  @page { margin: 20mm; }
                }
                body {
                  font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
                  line-height: 1.6;
                  color: #1a1a1a;
                }
              </style>
            </head>
            <body>
              ${exportContent.innerHTML}
            </body>
          </html>
        `);
        printWindow.document.close();

        setTimeout(() => {
          printWindow.print();
          printWindow.close();
        }, 250);
      }

      document.body.removeChild(exportContent);
    },
    []
  );

  const exportToClipboard = useCallback(async (messages: ChatMessage[]) => {
    let text = "AI Analysis Report\n";
    text += `Generated: ${format(new Date(), "MMMM d, yyyy 'at' h:mm a")}\n`;
    text += "=".repeat(50) + "\n\n";

    messages.forEach((message) => {
      if (message.role === "user") {
        text += `[You]: ${stripMarkdown(message.content)}\n\n`;
      } else {
        text += `[AI]: ${stripMarkdown(message.content)}\n\n`;
      }
    });

    await navigator.clipboard.writeText(text);
  }, []);

  return { exportToPDF, exportToClipboard };
}

function formatAnalysisBlock(block: AnalysisBlock): string {
  switch (block.type) {
    case "coverage":
      return `
        <div style="background: #eff6ff; border-left: 4px solid #3b82f6; padding: 16px; margin-bottom: 16px; border-radius: 0 8px 8px 0;">
          <p style="font-size: 13px; font-weight: 600; color: #1e40af; margin: 0 0 8px 0;">Data Coverage</p>
          <p style="font-size: 14px; color: #1e3a8a; margin: 0;">${block.title} - ${block.n} trades analyzed</p>
        </div>
      `;
    case "insights":
      return `
        <div style="background: #f0fdf4; border-left: 4px solid #22c55e; padding: 16px; margin-bottom: 16px; border-radius: 0 8px 8px 0;">
          <p style="font-size: 13px; font-weight: 600; color: #166534; margin: 0 0 8px 0;">${block.title}</p>
          <ul style="margin: 0; padding-left: 20px;">${block.items.map((item) => `<li style="font-size: 14px; color: #14532d; margin-bottom: 4px;">${item}</li>`).join("")}</ul>
        </div>
      `;
    case "recommendations":
      return `
        <div style="background: #fef3c7; border-left: 4px solid #f59e0b; padding: 16px; margin-bottom: 16px; border-radius: 0 8px 8px 0;">
          <p style="font-size: 13px; font-weight: 600; color: #92400e; margin: 0 0 8px 0;">${block.title}</p>
          <ul style="margin: 0; padding-left: 20px;">${block.items.map((item) => `<li style="font-size: 14px; color: #78350f; margin-bottom: 4px;">${item}</li>`).join("")}</ul>
        </div>
      `;
    case "callout":
      const bgColor = block.tone === "warning" ? "#fef3c7" : block.tone === "success" ? "#f0fdf4" : "#eff6ff";
      const borderColor = block.tone === "warning" ? "#f59e0b" : block.tone === "success" ? "#22c55e" : "#3b82f6";
      return `
        <div style="background: ${bgColor}; border-left: 4px solid ${borderColor}; padding: 16px; margin-bottom: 16px; border-radius: 0 8px 8px 0;">
          <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 8px 0;">${block.title}</p>
          <p style="font-size: 14px; color: #4b5563; margin: 0;">${block.body}</p>
        </div>
      `;
    case "stats":
      return `
        <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; margin-bottom: 16px; border-radius: 8px;">
          <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 12px 0;">${block.title}</p>
          ${block.rows.map((row) => `
            <div style="display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #f3f4f6;">
              <span style="font-size: 14px; color: #6b7280;">${row.label}</span>
              <span style="font-size: 14px; font-weight: 600; color: #111827;">${row.value}</span>
            </div>
          `).join("")}
        </div>
      `;
    case "querySummary":
      return `
        <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; margin-bottom: 16px; border-radius: 8px;">
          <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 8px 0;">${block.title}</p>
          <ul style="margin: 0; padding-left: 20px;">${block.bullets.map((bullet) => `<li style="font-size: 14px; color: #4b5563; margin-bottom: 4px;">${bullet}</li>`).join("")}</ul>
        </div>
      `;
    default:
      return "";
  }
}

function formatVisualization(viz: VizSpec): string {
  const { data, title } = viz;
  
  if (data.value !== undefined) {
    return `
      <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; border-radius: 8px; margin-bottom: 16px; text-align: center;">
        <p style="font-size: 12px; color: #6b7280; margin: 0 0 4px 0;">${data.label || title}</p>
        <p style="font-size: 28px; font-weight: 700; color: #111827; margin: 0;">${data.value}${data.unit || ""}</p>
        ${data.change !== undefined ? `<p style="font-size: 12px; color: ${data.change >= 0 ? "#059669" : "#dc2626"}; margin: 4px 0 0 0;">${data.change >= 0 ? "+" : ""}${data.change}${data.changeLabel || ""}</p>` : ""}
      </div>
    `;
  }

  if (data.comparison) {
    return `
      <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
        <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 12px 0;">${title}</p>
        <div style="display: flex; justify-content: space-around;">
          <div style="text-align: center;">
            <p style="font-size: 12px; color: #6b7280; margin: 0;">${data.comparison.a.label}</p>
            <p style="font-size: 20px; font-weight: 700; color: #111827; margin: 4px 0;">${data.comparison.a.value}</p>
          </div>
          <div style="text-align: center;">
            <p style="font-size: 12px; color: #6b7280; margin: 0;">${data.comparison.b.label}</p>
            <p style="font-size: 20px; font-weight: 700; color: #111827; margin: 4px 0;">${data.comparison.b.value}</p>
          </div>
        </div>
        ${data.comparison.delta !== undefined ? `<p style="text-align: center; font-size: 14px; color: #6b7280; margin: 12px 0 0 0;">Difference: ${data.comparison.delta}</p>` : ""}
      </div>
    `;
  }

  if (data.rows && data.rows.length > 0) {
    const columns = data.columns || [];
    return `
      <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
        <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 12px 0;">${title}</p>
        <table style="width: 100%; border-collapse: collapse;">
          ${columns.length > 0 ? `<tr>${columns.map((col) => `<th style="text-align: left; padding: 8px; font-size: 12px; color: #6b7280; border-bottom: 2px solid #e5e7eb;">${col.label}</th>`).join("")}</tr>` : ""}
          ${data.rows.slice(0, 10).map((row: any) => `<tr>${columns.map((col) => `<td style="padding: 8px; font-size: 14px; color: #374151; border-bottom: 1px solid #f3f4f6;">${row[col.key] ?? "-"}</td>`).join("")}</tr>`).join("")}
        </table>
        ${data.rows.length > 10 ? `<p style="font-size: 12px; color: #6b7280; margin: 8px 0 0 0; text-align: center;">+ ${data.rows.length - 10} more rows</p>` : ""}
      </div>
    `;
  }

  return `
    <div style="background: #f9fafb; border: 1px solid #e5e7eb; padding: 16px; border-radius: 8px; margin-bottom: 16px;">
      <p style="font-size: 13px; font-weight: 600; color: #374151; margin: 0 0 8px 0;">${title}</p>
      <p style="font-size: 14px; color: #6b7280; margin: 0;">Visualization available in interactive view</p>
    </div>
  `;
}
