"use client";

export const columnGroups: { label: string; ids: string[] }[] = [
  {
    label: "Core",
    ids: [
      "symbol",
      "tradeDirection",
      "open",
      "close",
      "holdSeconds",
      "volume",
      "profit",
      "commissions",
      "swap",
    ],
  },
  {
    label: "Tags",
    ids: ["killzone", "sessionTag", "modelTag", "protocolAlignment", "outcome"],
  },
  {
    label: "Compliance",
    ids: ["complianceStatus"],
  },
  {
    label: "Intent",
    ids: ["plannedRR", "plannedRiskPips", "plannedTargetPips"],
  },
  {
    label: "Opportunity",
    ids: [
      "manipulationPips",
      "mfePips",
      "maePips",
      "mpeManipLegR",
      "mpeManipPE_R",
      "maxRR",
      "rawSTDV",
      "rawSTDV_PE",
      "stdvBucket",
      "estimatedWeightedMPE_R",
    ],
  },
  {
    label: "Execution",
    ids: ["realisedRR", "rrCaptureEfficiency", "manipRREfficiency", "exitEfficiency"],
  },
  {
    label: "Expert advisor execution",
    ids: [
      "entrySpreadPips",
      "exitSpreadPips",
      "entrySlippagePips",
      "exitSlippagePips",
      "slModCount",
      "tpModCount",
      "partialCloseCount",
      "exitDealCount",
      "exitVolume",
      "entryDealCount",
      "entryVolume",
      "scaleInCount",
      "scaleOutCount",
      "trailingStopDetected",
      "entryPeakDurationSeconds",
      "postExitPeakDurationSeconds",
      "entryBalance",
      "entryEquity",
      "entryMargin",
      "entryFreeMargin",
      "entryMarginLevel",
    ],
  },
];

export const columnLabels: Record<string, string> = {
  manipulationPips: "Manipulation pips",
  mfePips: "Maximum favorable excursion (pips)",
  maePips: "Maximum adverse excursion (pips)",
  mpeManipLegR: "Maximum price excursion manipulation leg (risk units)",
  mpeManipPE_R: "Maximum price excursion manipulation post exit (risk units)",
  maxRR: "Maximum reward to risk",
  realisedRR: "Realised reward to risk",
  rrCaptureEfficiency: "Reward to risk capture efficiency (percent)",
  manipRREfficiency: "Manipulation reward to risk efficiency (percent)",
  exitEfficiency: "Exit efficiency (percent)",
  rawSTDV: "Raw standard deviation",
  rawSTDV_PE: "Raw standard deviation post exit",
  stdvBucket: "Standard deviation (bucket)",
  estimatedWeightedMPE_R: "Estimated weighted maximum price excursion (risk units)",
  plannedRR: "Planned reward to risk",
  plannedRiskPips: "Planned risk (pips)",
  plannedTargetPips: "Planned target (pips)",
  entrySpreadPips: "Entry spread (pips)",
  exitSpreadPips: "Exit spread (pips)",
  entrySlippagePips: "Entry slippage (pips)",
  exitSlippagePips: "Exit slippage (pips)",
  slModCount: "Stop loss modifications",
  tpModCount: "Take profit modifications",
  partialCloseCount: "Partial closes",
  exitDealCount: "Exit deals",
  exitVolume: "Exit volume",
  entryDealCount: "Entry deals",
  entryVolume: "Entry volume",
  scaleInCount: "Scale in",
  scaleOutCount: "Scale out",
  trailingStopDetected: "Trailing stop",
  entryPeakDurationSeconds: "Time to peak",
  postExitPeakDurationSeconds: "Time to post exit peak",
  entryBalance: "Entry balance",
  entryEquity: "Entry equity",
  entryMargin: "Entry margin",
  entryFreeMargin: "Entry free margin",
  entryMarginLevel: "Entry margin level",
  outcome: "Outcome",
  complianceStatus: "Compliance status",
};

export const columnTooltips: Record<string, string> = {
  symbol: "The name of what you traded.",
  tradeDirection: "Shows if you bought or sold.",
  open: "When the trade started.",
  close: "When the trade ended.",
  holdSeconds: "How long the trade stayed open.",
  volume: "How big the trade was.",
  profit: "How much money you made or lost.",
  commissions: "Fees the broker took.",
  swap: "Overnight fee or credit.",
  killzone: "Old name for the session tag.",
  sessionTag: "Shows the time window name for this trade.",
  modelTag: "Shows the setup name you used.",
  protocolAlignment: "Shows if you followed your rules.",
  outcome: "Shows if you won, lost, broke even, or won part.",
  complianceStatus: "Shows if the trade passed your rules.",
  plannedRR: "The reward to risk you planned.",
  plannedRiskPips: "How far your stop was in pips.",
  plannedTargetPips: "How far your target was in pips.",
  manipulationPips: "How big the setup move was.",
  mfePips: "How far price went your way while you were in.",
  maePips: "How far price went against you while you were in.",
  mpeManipLegR: "How big the best move was, using the setup move.",
  mpeManipPE_R: "How big the after-exit move was, using the setup move.",
  maxRR: "The biggest reward to risk you could have had.",
  realisedRR: "The reward to risk you actually got.",
  rrCaptureEfficiency: "How much of the possible move you kept.",
  manipRREfficiency: "How much of the setup move you kept.",
  exitEfficiency: "How good your exit timing was.",
  rawSTDV: "How wild price was while you were in.",
  rawSTDV_PE: "How wild price was after you exited.",
  stdvBucket: "A simple label for how wild price was.",
  estimatedWeightedMPE_R: "A realistic target based on your past trades.",
  entrySpreadPips: "How wide the spread was when you entered.",
  exitSpreadPips: "How wide the spread was when you exited.",
  entrySlippagePips: "How far price slipped when you entered.",
  exitSlippagePips: "How far price slipped when you exited.",
  slModCount: "How many times stop loss changed.",
  tpModCount: "How many times take profit changed.",
  partialCloseCount: "How many times you closed a part.",
  exitDealCount: "How many exit deals were used.",
  exitVolume: "Total size closed at exit.",
  entryDealCount: "How many entry deals were used.",
  entryVolume: "Total size opened at entry.",
  scaleInCount: "How many extra entries you added.",
  scaleOutCount: "How many extra exits you added.",
  trailingStopDetected: "Shows if stop loss moved to follow price.",
  entryPeakDurationSeconds: "Time from entry to the best price.",
  postExitPeakDurationSeconds: "Time from exit to the best price after.",
  entryBalance: "Balance when you entered.",
  entryEquity: "Equity when you entered.",
  entryMargin: "Margin used at entry.",
  entryFreeMargin: "Free margin at entry.",
  entryMarginLevel: "Margin level at entry.",
};

export function formatColumnLabel(raw: string) {
  const parts = raw.split(" ");
  return parts
    .map((word, index) => {
      if (index === 0) return word;
      if (/^[A-Z0-9/:%().]+$/.test(word)) return word;
      return word.toLowerCase();
    })
    .join(" ");
}
